name = "api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
# Add your environment variables here

[[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"

[[r2_buckets]]
# binding = "MY_R2_BUCKET"
# bucket_name = "your-r2-bucket-name"